# Generated by Django 2.2.16 on 2021-01-04 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bucket',
                'ordering': ['-date_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('done', models.BooleanField(default=False)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.Bucket')),
            ],
            options={
                'db_table': 'task',
                'ordering': ['done', '-date_modified'],
                'abstract': False,
            },
        ),
    ]
